name: Streamlit Github actions

on:
  push:
     branches: [main]
jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:
      - uses: actions/checkout@v2
      
      - name: Build a Docker image
        run: docker build -f Dockerfile -t app:latest .

      - name: Run the Docker container
        run: docker run -p 8501:8501 app:latest
