name: Streamlit Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myimage:latest

    - name: Run the Docker container
      run: docker run --rm -p 8501:8501 myimage:latest
